import streamlit as st
import requests
import datetime

# from exception.exceptions import TradingBotException

BASE_URL = "http://localhost:8000"  # Backend endpoint

st.set_page_config(
    page_title="🌍 Travel Planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.markdown(
    """
    <style>
    .app-shell {
        background: linear-gradient(120deg, #f6f9ff 0%, #fef8f1 100%);
        border: 1px solid #e7ecf5;
        border-radius: 16px;
        padding: 1rem;
    }
    .activity-card {
        background: #ffffff;
        border-left: 5px solid #0ea5a4;
        padding: 0.75rem 0.9rem;
        margin: 0.45rem 0;
        border-radius: 10px;
        box-shadow: 0 8px 24px rgba(15, 23, 42, 0.06);
        animation: fadeSlideIn 0.45s ease both;
    }
    .activity-label {
        font-weight: 700;
        color: #1f2937;
        margin-bottom: 0.2rem;
    }
    .activity-detail {
        color: #475569;
        font-size: 0.92rem;
        word-break: break-word;
    }
    .pulse-dot {
        display: inline-block;
        width: 8px;
        height: 8px;
        border-radius: 50%;
        background: #0ea5a4;
        margin-right: 8px;
        animation: pulse 1.5s infinite;
        vertical-align: middle;
    }
    @keyframes pulse {
        0% { transform: scale(0.9); opacity: 0.7; }
        70% { transform: scale(1.35); opacity: 0; }
        100% { transform: scale(0.9); opacity: 0; }
    }
    @keyframes fadeSlideIn {
        from { opacity: 0; transform: translateY(8px); }
        to { opacity: 1; transform: translateY(0); }
    }
    </style>
    """,
    unsafe_allow_html=True,
)

st.title("🌍 Travel Planner Agentic Application")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

if "activity" not in st.session_state:
    st.session_state.activity = []


def render_activity_trace(trace_items):
    st.subheader("Agent Activity")
    if not trace_items:
        st.info("No activity yet. Submit a trip request to see what the agent does.")
        return

    for item in trace_items:
        label = item.get("label", "Agent Step")
        detail = item.get("detail", "")
        st.markdown(
            f"""
            <div class="activity-card">
                <div class="activity-label"><span class="pulse-dot"></span>{label}</div>
                <div class="activity-detail">{detail}</div>
            </div>
            """,
            unsafe_allow_html=True,
        )

# Display chat history
st.header("How can I help you in planning a trip? Let me know where do you want to visit.")

# Chat input box at bottom
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder="e.g. Plan a trip to Goa for 5 days")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        # Show staged agent progress while backend processes.
        progress_placeholder = st.empty()
        status_placeholder = st.empty()
        progress_bar = progress_placeholder.progress(0, text="Preparing agent workflow...")

        payload = {"question": user_input}
        status_placeholder.markdown("### 🤖 Live Execution\nInitializing model and tools...")
        progress_bar.progress(20, text="Analyzing your travel request...")

        response = requests.post(f"{BASE_URL}/query", json=payload)
        progress_bar.progress(75, text="Collecting tool outputs and drafting itinerary...")

        if response.status_code == 200:
            response_payload = response.json()
            answer = response_payload.get("answer", "No answer returned.")
            agent_trace = response_payload.get("agent_trace", [])

            st.session_state.activity = agent_trace

            progress_bar.progress(100, text="Done. Rendering travel plan and execution trace.")
            status_placeholder.empty()
            progress_placeholder.empty()

            markdown_content = f"""# 🌍 AI Travel Plan

            # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
            # **Created by:** Atriyo's Travel Agent

            ---

            {answer}

            ---

            *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
            """
            st.markdown(markdown_content)
        else:
            st.error(" Bot failed to respond: " + response.text)

    except Exception as e:
        st.error(f"The response failed due to {e}")

if st.session_state.activity:
    with st.container(border=True):
        render_activity_trace(st.session_state.activity)